---
logging:
  level:
    .: error
    org.springframework: ERROR

---
spring:
  config:
    activate:
      on-profile: development-profile
  datasource:
    url: jdbc:mariadb://localhost:3306/restaurant_manager
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true